// <auto-generated />
namespace AttendanceApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class relatedappuserpositionadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(relatedappuserpositionadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201811201935575_relatedappuser-position-added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
